
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-25T13:37:34-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "1ac4bc0477208dc304c86083434bdba08d787d4d",
 "version": "2.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
